website/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user
from .models import User, Post, Like, Comment, Dislike, ReplyComment, CommentLike
from . import db
from sqlalchemy import desc, and_, or_ # can descending order the oder_by database. or_ is for multiple search termers


views = Blueprint('views', __name__)
months = {1:"January",2:"February",3:"March",4:"April",5:"May",6:"June",7:"July",8:"August",9:"September",10:"October",11:"November",12:"December"}

@views.route('/home/', methods=['GET','POST'])
@login_required 
def home():
    posts = db.session.query(Post, User).join(User, Post.user_id == User.id).order_by(Post.date.desc()).limit(10).all()
    if request.method == "POST":
        if request.form.get("search") != None:
            search = request.form.get('search')
            return redirect(url_for("views.search", search=search))
    else:
        return render_template("home.html", user=current_user, page="Home", posts=posts, current_user=current_user)


@views.route('/profile/') # redirect you to your own profile
@login_required
def profile_redirect():
    return redirect('/profile/%s' % current_user.id)

@views.route('/profile/<int:id>', methods=["GET","POST"])
@login_required
def user_profile(id):
    if request.method == "GET":
        # try:
        user = User.query.get(id)
        posts = Post.query.filter_by(user_id=id).order_by(Post.date.desc()).limit(5).all()

        name = user.first_name + " " + user.last_name
        pagename = name + "'s Profile"
        date_joined = str(user.date_joined).split(" ")[0] # date_joined = the "2023-06-11 12:34:56" but split at the space, and only take the first value of the list.
        date_joined_list = date_joined.split("-")
        year = date_joined_list[0]
        if date_joined_list[1][0] == "0":
            string = date_joined_list[1][1:]
            month = months.get(int(string))
        else:
            month = months.get(date_joined_list[1])
        day = date_joined_list[2]
        date_joined = str(month) + " " + str(day) + ", " + str(year)


        return render_template("user_profile.html", page=pagename, name=name, user=user, id=int(id), date_joined=date_joined, posts=posts, current_user=current_user)
        # except Exception as e:
        #     return render_template("404.html", page="Error 404 Not Found", error="The user you are looking for doesn't exist.", user=current_user)
    elif request.method == "POST":
        if request.form.get("post") != None:
            post = request.form.get("post")
            title = request.form.get('title')
            new_post = Post(data=post, user_id=current_user.id, title=title)
            db.session.add(new_post)
            db.session.commit()
            
            return redirect('/profile/%s' % id)
        

@views.route('/edit/profile/')
@login_required
def redirect_to_edit_profile():
    return redirect("/edit/profile/%s" % current_user.id)

@views.route('/post/<int:id>', methods=['GET','POST'])
@login_required
def view_post(id):

    previous_page = request.referrer
    post = Post.query.get(id)
    user = User.query.get(post.user_id)

    
    like = Like.query.filter_by(user=current_user, post=post).first()
    liked = like

    dislike = Dislike.query.filter_by(user=current_user, post=post).first()
    disliked = dislike

    comments = Comment.query.filter_by(post=post).order_by(Comment.date.desc()).all()


    date = str(post.date).split(" ")[0]



    try:
        return render_template("view_post.html", page="Post", user=user, post=post, current_user=current_user, liked=liked, comments=comments, date=date, disliked=disliked)
    except Exception as e:
        print(e)
        return render_template("404.html", error="This post doesn't exist.", user=user, current_user=current_user)


@views.route('/delete/post/<int:id>')
@login_required
def delete_post(id):
    post = Post.query.get(id)
    previous_page = request.referrer
    if id == None:
        flash("You can only delete your own posts.", category="error")
        return redirect(url_for("views.home"))
    else:
        try:
            if int(current_user.id) == int(post.user_id):
                db.session.delete(post)
                db.session.commit()
                flash("Post deleted.", category="success")
                return redirect("/profile/")
            else: # this is actually unneeded because flask automatically sets the post to None if it's not the user's post, so that's why we have try and except.
                flash("You can only delete your own posts.", category="error")
                return redirect("/profile/")
        except Exception as e:
            flash("You can only delete your own posts.", category="error")
            print(e)
            return redirect(url_for("views.home"))
        
@views.route('/search/')
@login_required
def empty_search_handler():
    previous_page = request.referrer
    return redirect(previous_page)

@views.route("/search/<search>", methods=['GET','POST'])
@login_required
def search(search):
    if request.method == "POST":
        if request.form.get("search") != None:
            search = request.form.get('search')
            return redirect("/search/%s" % search)
    else:
        # posts = Post.query.filter(Post.data.ilike(f"%{search}%")).all()
        posts = db.session.query(Post, User).join(User, Post.user_id == User.id).filter(
            or_(Post.data.ilike(f"%{search}%"), Post.title.ilike(f"%{search}%"))).all()
        # users = User.query.filter(User.first_name.ilike(f"%{search}%")).all()
        full_name = User.first_name + " " + User.last_name
        if len(search) > 2: # to make sure all the users don't show up from something like search term "a"
            users = User.query.filter(
                or_(User.first_name.ilike(f"%{search}%"), User.last_name.ilike(f"%{search}%"), full_name.ilike(f"%{search}%"))).all()
        else:
            users = None
        


        return render_template('search.html', posts=posts, users=users, query=search, user=current_user, current_user=current_user, page="Search")
    
@views.route('/post/<int:post_id>/like', methods=["POST"])
@login_required
def like_post(post_id):
    previous_page = request.referrer
    post = Post.query.get_or_404(post_id)
    like = Like.query.filter_by(user=current_user, post=post).first()
    # make sure they can't dislike and like
    dislike = Dislike.query.filter_by(user=current_user, post=post).first()
    #check if the current user has already liked the post
    if like:
        # user has already liked the post, so we'll remove the like
        db.session.delete(like)
    else:
        if dislike: # make sure they can't dislike and like
            db.session.delete(dislike)
        # user hasn't liked the post, so we'll add a like
        like = Like(user=current_user, post=post)
        db.session.add(like)
    db.session.commit()
    
    return redirect(previous_page)

@views.route('/post/<int:post_id>/dislike', methods=["POST"])
@login_required
def dislike_post(post_id):
    previous_page = request.referrer
    post = Post.query.get_or_404(post_id)
    dislike = Dislike.query.filter_by(user=current_user, post=post).first()
    # we want to make sure that if they dislike it when they already liked it, the like is removed and replaced.
    like = Like.query.filter_by(user=current_user, post=post).first()
    #check if already disliked by current user
    if dislike:
        db.session.delete(dislike)
    else:
        if like: # make sure they can't dislike and like
            # user has already liked the post, so we'll remove the like
            db.session.delete(like)
        dislike = Dislike(user=current_user, post=post)
        db.session.add(dislike)

    db.session.commit()

    return redirect(previous_page)

@views.route("/post/<int:post_id>/comment/<int:comment_id>/like", methods=["POST"])
@login_required
def like_comment(post_id, comment_id):
    comment = Comment.query.get_or_404(comment_id)
    post = Post.query.get_or_404(post_id)
    comment_like = CommentLike.query.filter_by(user=current_user, comment=comment).first()

    if comment_like:
        db.session.delete(comment_like)
    else:
        comment_like = CommentLike(user=current_user, comment=comment, post=post)
        db.session.add(comment_like)
    db.session.commit()

    return redirect(request.referrer)

@views.route('/post/<int:id>/comment/', methods=["POST"])
@login_required
def comment_on_post(id):
    comment_data = request.form.get("comment")
    post = Post.query.get(id)

    comment = Comment(user=current_user, data=comment_data, post=post)
    db.session.add(comment)
    db.session.commit()


    return redirect(request.referrer)

@views.route('/delete/comment/<int:id>')
@login_required
def delete_comment(id):
    comment = Comment.query.get(id)
    if id == None:
        flash("You can only delete your own comments.", category="error")
        return redirect(url_for("views.home"))
    else:
        try:
            if int(current_user.id) == int(comment.user_id):
                db.session.delete(comment)
                db.session.commit()
                flash("Comment deleted.", category="success")
                return redirect(request.referrer)
            else: #technically uneeded. (See delete_post())
                flash("You can only delete your own comments.", category="error")
                return redirect(request.referrer)
        except Exception as e:
            flash("You can only delete your own posts.", category="error")
            print(e)
            return redirect(request.referrer)
        

@views.route('/comment/<int:id>/reply/', methods=["POST"])
@login_required
def reply_to_comment(id):
    reply_data = request.form.get("reply")
    print(reply_data)
    comment = Comment.query.get(id)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% block head %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="static/style.css" />
    {%block extra_css%}{% endblock %}
    <title>{%block title%}Social Media | {{page}}{%endblock%}</title>
  </head>
  {% endblock %}
  <body>
    {% if user.is_authenticated %}
    <nav
      class="navbar navbar-expand-lg bg-body-tertiary"
      data-bs-theme="dark"
      style="
        background: #2e5266 !important;
        position: fixed;
        width: 100%;
        z-index: 1000;
      "
    >
      <div class="container-fluid">
        <a class="navbar-brand" href="/home/">Social Media</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="/home/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/profile/">My Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/edit/profile/">Settings</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <br /><br /><br />
    {% else %} {% endif %} {% with messages =
    get_flashed_messages(with_categories=true) %} {% if messages %} {% for
    category, message in messages %} {% if category == 'error' %}
    <div class="alert alert-danger alert-dismissable fade show" role="alert">
      {{ message }}
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {% elif category == 'primary' %}
    <div class="alert alert-primary alert-dismissable fade show" role="alert">
      {{ message }}
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissable fade show" role="alert">
      {{ message }}
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %} {% block body %}{%
    endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
      integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS"
      crossorigin="anonymous"
    ></script>
    <!-- <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"></script> THIS IS HOW YOU ADD JAVASCRIPT-->
  </body>
</html>

website/templates/edit_user_profile.html
{% extends 'base.html' %} {% block body %} <br /><br />
<div class="container">
  <h1>Settings</h1>
  <a href="/edit/profile/{{current_user.id}}/profile_picture" class="btn btn-outline-primary">Change Profile Picture</a>
  <form method="post">
    <table class="">
     
      <tr>
        <label>Name
        <td class="signup">
          <input
            type="text"
            name="first_name"
            placeholder="First Name"
            class="form-control"
            value="{{current_user.first_name}}"
            
          />
        </td>
        <td class="signup-boxes">
          <input
            type="text"
            name="last_name"
            placeholder="Last Name"
            class="form-control"
            value="{{current_user.last_name}}"
          />
        </td></label>
        </tr>
     
      <tr>
        <td class="signup-boxes" colspan="2"><label for="">Email
          <input
            type="email"
            name="email"
            placeholder="Email"
            class="form-control"
            value="{{current_user.email}}"
           
          /></label><br><label for="">Password</td></tr>
          
          <tr> 
        <td class="signup-boxes" colspan="2"> 
          <input
            type="password"
            name="old_password"
            placeholder="Type your old password"
            class="form-control"
            id="password"
          />
        </td>
      </tr>
      <tr>
        <td class="signup-boxes" colspan="1">
          <input
            type="password"
            name="password1"
            placeholder="New Password"
            class="form-control"
          />
        </td>

        <td class="signup-boxes" colspan="1">
          <input
            type="password"
            name="password2"
            placeholder="Type new password again"
            class="form-control"
          />
        </td>
      </tr>
      <tr>
        <td class="signup-boxes" colspan="2"><label for="">Your Bio</label>
            {% if current_user.bio == None or current_user.bio == "" %}
            <textarea name="bio" cols="30" rows="10" placeholder="Enter your bio" class="form-control"></textarea>
            {% else %}
            <textarea name="bio" cols="30" rows="10" placeholder="Enter your bio (max 1,500 characters). Markup (HTML) supported." class="form-control" maxlength="1500">{{current_user.bio}}</textarea>
            {% endif %} 
        </td>
      </tr> 
      
      <tr>
        <td class="signup-boxes" colspan="2"><br>
          <input
            type="submit"
            class="btn btn-primary form-control signup-boxes"
            value="Update Profile"
          /></label>
        </td>
      </tr>
    </table>
  </form>
  <br><br>
  <a href="/logout" class="btn btn-outline-danger">Log Out</a><br><br><br><br>
</div>
{% endblock %}

website/templates/edit_user_profile_picture.html
{% extends 'base.html' %} {% block body %}

<div class="container">
  <form
    action="/edit/profile/{{user.id}}/profile_picture/"
    method="post"
    enctype="multipart/form-data"
  >
    <input
      type="file"
      id="img"
      name="profile_picture"
      accept="image/*"
      class="form-control"
    />
    <br />
    <input type="submit" class="btn btn-primary form-control" />
  </form>
  <br /><br /><br />
  <h3>Your Profile Photo</h3>
  {% if user.profile_picture %}
  <img
    src="/static/profile_pictures/{{user.profile_picture}}"
    alt="Avatar Image"
    style="border-radius: 50%; width: 150px; height: 150px"
  />
  <a
    href="/edit/profile/{{user.id}}/remove_profile_picture/"
    class="btn btn-sm btn-outline-primary"
    >Remove Profile Photo</a
  >
  {% else %}
  <img
    src="/static/default_profile_photo.jpg"
    alt="Avatar Image"
    style="border-radius: 50%; width: 150px; height: 150px"
  />
  {% endif %}
</div>

{% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block body %}
<div class="container">
  <form action="" method="post">
    <div class="input-group mb-3">
      <input
        type="text"
        class="form-control"
        placeholder="Search..."
        aria-label="Search"
        aria-describedby="button-addon2"
        name="search"
      />
      <input
        class="btn btn-outline-primary"
        type="submit"
        id="button-addon2"
        value="Search"
      >

      </button>
    </div>
  </form>
  <h1>Recent Posts</h1>
  {% for post, user in posts %}
  <div class="border" style="border-radius: 10px; padding: 5px">
    <a href="/profile/{{user.id}}" style="text-decoration: none;">
      <img
        src="../static/profile_pictures/{{user.profile_picture}}"
        alt="Avatar Image"
        style="border-radius: 50%; width: 30px; height: 30px"
      />
    <a href="/profile/{{user.id}}" style="color: #6e8898; text-decoration: none;"><small>{{ user.first_name }} {{ user.last_name }}</small></a>

    <h5><a href="/post/{{post.id}}" style="color:black;text-decoration: none;"><strong>{{ post.title }}</strong></a></h5>
    <p>{{ post.data | nl2br }}</p>
        <!-- Liking Post -->
        <form action="/post/{{post.id}}/like" method="post" style="display:inline">
          <input type="submit" class="btn btn-danger btn-sm" value="👍" />
          <p style="display: inline"> {{ post.likes | count }}</p>
        </form>
            <!-- Disliking post -->
          <form
            action="/post/{{post.id}}/dislike"
            method="post"
            style="display: inline"
          >
            <input type="submit" class="btn btn-danger btn-sm" style="display:inline" value="👎" />
            <p style="display: inline">{{ post.dislikes | count }}</p>
          </form>
    
    <br>
        <!-- Comment count -->
        {% if post.comments | count == 1 %}
        <small><a href="/post/{{post.id}}" style="color: black;">{{ post.comments | count }} Comment</a></small>
        {% else %}
        <small><a href="/post/{{post.id}}" style="color: black;">{{ post.comments | count }} Comments</a></small>
        {% endif %}
    
  </div>
  <br />
  {% endfor %}
</div>
{% endblock %}

website/templates/login_page.html
{% extends 'base.html' %}

{% block extra_css %}
<link rel="stylesheet" href="static/fade_in.css">
{% endblock %}

{% block body %}
<table class="login-table">
  <tr>
    <td class="login-th">
      <h1 style="font-size: 500%;">Social Media</h1>
      <h6>
        Where you can meet your friends, comment, and stay up to date.
      </h6>
    </td>
    
    <td class="login-th">
      <div class="input-group mb-3">
        <form action="" method="post">
          <input
            type="email"
            name="email"
            placeholder="Email"
            class="form-control"
          />
          <input
            type="password"
            name="password"
            placeholder="Password"
            class="form-control"
          />
          <span class="d-grid gap-2">
            <input type="submit" class="btn btn-primary form-control" value="Log In" />
          </span>
        </form>
      <!-- <div class="form-text form-control mb-3 border-0">
            <p>Don't have an account?</p>
            <a href="sign-up" class="btn btn-success btn-sm">Sign Up</a>
            </div> -->
        </form>
        
      </div>
      <p class="form-text">Don't have an account?
      <a href="sign-up" class="form-text" style="color:black">Sign Up</a></p>

    </td>
  </tr>
</table>
{% endblock %}

website/templates/user_profile.html
{% extends 'base.html' %} {%block body%}
<div class="container">
  <br /><br />
  <h2>
    {% if user.profile_picture %}

    <img src="../static/profile_pictures/{{user.profile_picture}}" alt="Avatar Image" style="border-radius: 50%; width: 150px; height: 150px">

    {% else %}
    <img
      src="../static/profile_pictures/default_profile_photo.jpg"
      alt="Avatar image" style="border-radius: 50%; width: 150px; height: 150px"
    /> {% endif %}
    <span style="padding: 20px">{{name}}</span>
  </h2>
  {% if id == current_user.id %}
  <a
    href="/edit/profile"
    style="font-size: small"
    class="btn btn-secondary btn-sm"
    >Edit your profile</a
  >
  <!-- ACCORDION -->
  <br /><br />
  <div class="accordion">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button
          class="accordion-button"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapseOne"
          aria-expanded="true"
          aria-controls="collapseOne"
        >
          Create Post
        </button>
      </h2>
      <div
        id="collapseOne"
        class="accordion-collapse collapse"
        data-bs-parent="#accordionExample"
      >
        <div class="accordion-body">
          <!-- FORM -->
          <form method="post">
            <input
              type="text"
              name="title"
              class="form-control"
              placeholder="Title of Post"
              required
            />
            <textarea
              name="post"
              cols="30"
              rows="10"
              class="form-control"
              placeholder="Write a post here..."
              maxlength="10000"
              required
            ></textarea
            ><br />
            <input
              type="submit"
              value="Create Post"
              class="form-control btn btn-primary"
            />
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- ACCORDION END -->

  {% else %} {% endif %} <br />
  <h4>Recent Posts</h4>
  {% if posts %}{% else %}
  <p>This user has no posts.</p>
  {% endif %} {% for post in posts %}
  <div class="border" style="border-radius: 10px; padding: 5px">
    <a href="/post/{{post.id}}" style="color: black; text-decoration: none"
      ><h5>{{post.title}}</h5></a
    >
    <p>{{ post.data | nl2br }}</p>
    <small
      >{% if id == current_user.id %}
      <a
        href="{{ url_for('views.delete_post', id=post.id) }}"
        onclick="return confirm('Are you sure you want to delete this post?')"
        class="btn btn-sm btn-warning"
        >Delete Post</a
      ></small
    >{% endif %}
    <!-- Liking Post -->
    <form action="/post/{{post.id}}/like" method="post" style="display: inline">
      <input type="submit" class="btn btn-danger btn-sm" value="👍" />
      <p style="display: inline">{{ post.likes | count }}</p></form>
      <!-- Disliking post -->
      <form
        action="/post/{{post.id}}/dislike"
        method="post"
        style="display: inline"
      >
        <input type="submit" class="btn btn-danger btn-sm" value="👎" />
        <p style="display: inline">{{ post.dislikes | count }}</p>
      </form>

      <!-- Comment count -->
      <br />
      {% if post.comments | count == 1 %}
      <small>{{ post.comments | count }} Comment</small>
      {% else %}
      <small>{{ post.comments | count }} Comments</small>
      {% endif %}
    </form>
  </div>

  <br />
  {% endfor %}

  <br />

  <h4>Bio</h4>
  {% if user.bio == None or user.bio == "" %}
  <p>This user has no bio.</p>
  {% else %}
  <div class="container border" style="border-radius: 10px;">
  <p class="" style="padding: 10px">{{user.bio | nl2br}}</p></div><br>
  {% endif %}
  <p><b>Date Joined: </b>{{date_joined}}</p>
  <!-- The nl2br is a new line and I'm filtering out the variable so it shows newlines. -->
</div>
{%endblock%}

website/templates/view_post.html
{% extends 'base.html' %} {% block body %}
<div class="container">
  <h2>{{ post.title }}</h2>
  <p>
    <a
      href="/profile/{{user.id}}"
      style="color: #6e8898; text-decoration: none"
    >
      <img
        src="../static/profile_pictures/{{user.profile_picture}}"
        alt="Avatar Image"
        style="border-radius: 50%; width: 50px; height: 50px"
      />
      {{ user.first_name }} {{ user.last_name }}</a
    >
    - {{ date }}
  </p>
  <p>{{ post.data | nl2br }}</p>

  {% if current_user.id == post.user_id %}
  <br />
  <small
    ><a
      href="/delete/post/{{post.id}}"
      onclick="return confirm('Are you sure you want to delete this post?')"
      class="btn btn-sm btn-warning"
      >Delete Post</a
    ></small
  >
  {% else %}{% endif %}
  <!-- Liking post -->
  <form action="/post/{{post.id}}/like" method="post" style="display: inline">
    <input type="submit" class="btn btn-danger btn-sm" value="👍" />
    <p style="display: inline">{{ post.likes | count }}</p>
  </form>
  <!-- Disliking post -->
  <form
    action="/post/{{post.id}}/dislike"
    method="post"
    style="display: inline"
  >
    <input type="submit" class="btn btn-danger btn-sm" value="👎" />
    <p style="display: inline">{{ post.dislikes | count }}</p>
  </form>

  <br /><br />
  <h3>Comments ({{ post.comments | count }})</h3>
  <!-- ACCORDION -->

  <div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button
          class="accordion-button"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapseOne"
          aria-expanded="true"
          aria-controls="collapseOne"
        >
          Add Comment
        </button>
      </h2>
      <div
        id="collapseOne"
        class="accordion-collapse collapse"
        data-bs-parent="#accordionExample"
      >
        <div class="accordion-body">
          <!-- FORM -->
          <form method="post" action="/post/{{ post.id }}/comment/">
            <textarea
              name="comment"
              cols="30"
              rows="1"
              class="form-control"
              placeholder="Write your comment..."
              maxlength="1000"
              required
            ></textarea
            ><br />
            <input
              type="submit"
              value="Add Comment"
              class="form-control btn btn-primary"
            />
          </form>
        </div>
      </div>
    </div>
  </div>
  <br />
  <!-- ACCORDION END -->
  {% for comment in comments %}
  <div class="border" style="border-radius: 10px; padding: 5px">
    <a
      href="/profile/{{ comment.user.id }}"
      style="color: black; text-decoration: none"
    >
      <img
        src="../static/profile_pictures/{{comment.user.profile_picture}}"
        alt="Avatar Image"
        style="border-radius: 50%; width: 30px; height: 30px"
      />

      <strong
        >{{ comment.user.first_name }} {{ comment.user.last_name }}</strong
      ></a
    >
    <p>{{ comment.data }}</p>
    <form
      action="/post/{{post.id}}/comment/{{comment.id}}/like"
      method="post"
      style="display: inline"
    >
      <input type="submit" class="btn btn-danger btn-sm" value="👍" />
      <p style="display: inline">{{ comment.comment_likes | count }}</p>
    </form>
    {% if comment.user == current_user %}
    <a
      href="{{ url_for('views.delete_comment', id=comment.id) }}"
      onclick="return confirm('Are you sure you want to delete this comment?')"
      class="btn btn-sm btn-warning"
      >Delete Comment</a
    >
    {% endif %}
    <a
      data-bs-toggle="collapse"
      href="#collapseReply{{comment.id}}"
      class="btn btn-sm btn-primary"
      >Reply</a
    >

    <a
      data-bs-toggle="collapse"
      href="#collapseComments{{comment.id}}"
      class="btn btn-sm btn-success"
      >Show Replies ({{ comment.replies | count }})</a
    >
    <!-- REPLY TO COMMENT Collapse -->
    <div class="collapse" id="collapseReply{{comment.id}}">
      <br />
      <div class="">
        <form
          action="{{ url_for('views.reply_to_comment', id=comment.id )}}"
          method="post"
        >
          <input
            type="text"
            name="reply"
            class="form-control"
            placeholder="Write your reply..."
            required
          />
          <input
            type="submit"
            value="Add reply"
            class="btn btn-primary form-control"
          />
        </form>
      </div>
    </div>
    <!-- Add Comment Collapse -->
    <div class="collapse" id="collapseComments{{comment.id}}">
      <br />
      {% if comment.replies | count == 0 %}
      <p>There are no replies.</p>
      {% endif %} {% for reply in comment.replies %}
      <p><a href="/profile/{{user.id}}" style="text-decoration: none;">
        <img
          src="../static/profile_pictures/{{reply.user.profile_picture}}"
          alt="Avatar Image"
          style="border-radius: 50%; width: 20px; height: 20px"
        />
        <strong
          ><a
            href="/profile/{{reply.user.id}}"
            style="text-decoration: none; color: black"
            >{{ reply.user.first_name }} {{ reply.user.last_name }}</a
          ></strong
        >
        {{ reply.data }} {% set date = reply.date|string %} {% set date =
        date.split(" ") %} <br />
        <small
          >({{ date[0] }}) {% if reply.user == current_user %}
          <a
            href="/delete/reply/{{ reply.id }}"
            onclick="return confirm('Are you sure you want to delete this reply?')"
            >Delete</a
          >
          {% endif %}
        </small>
      </p>

      {% endfor %}
    </div>
  </div>
  <br />
  {% endfor %}
</div>

{% endblock %}